### ISSUE TITLE
Connection not working anymore after update home-assistant to version 2024.07 or 2024.07.1

### ISSUE THREAD

**Issue by JohanCl** [Arbuzov/home_assistant_delonghi_primadonna#103]
This integration was always working great but after home assistant upgrade to version 2024.07, 2024.07.1 and 2024.07.02 there is no active communication anymore with the machine.
 Part of the diagnostic log:
INFO (MainThread) [custom_components.delonghi_primadonna.device] Connect to XX.XX.XX.XX.XX.XX
WARNING (MainThread) [custom_components.delonghi_primadonna.device] BleakError: No backend with an available connection slot that can reach address XX.XX.XX.XX.XX.XX was found
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/delonghi_primadonna/device.py", line 302, in power_on
    await self.send_command(BYTES_POWER)
  File "/config/custom_components/delonghi_primadonna/device.py", line 403, in send_command
    await self._connect()
  File "/config/custom_components/delonghi_primadonna/device.py", line 234, in _connect
    raise error
  File "/config/custom_components/delonghi_primadonna/device.py", line 228, in _connect
    await self._client.connect()
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 285, in connect
    wrapped_backend = self._async_get_best_available_backend_and_device(manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 394, in _async_get_best_available_backend_and_device
    raise BleakError(
bleak.exc.BleakError: No backend with an available connection slot that can reach address XX:XX:XX:XX:XX:XX was found

**Comment by Arbuzov** [comment]
Fixed
