### ISSUE TITLE
Integration does not start properly anymore after update to Homeassistant 2202.10

### ISSUE THREAD

**Issue by pail23** [Arbuzov/home_assistant_delonghi_primadonna#14]
I get the following error in the log:
Traceback (most recent call last):
  File "/config/custom_components/delonghi_primadonna/device.py", line 262, in get_device_name
    await self._connect()
  File "/config/custom_components/delonghi_primadonna/device.py", line 153, in _connect
    .find_device_by_address(
AttributeError: 'HaBleakScannerWrapper' object has no attribute 'find_device_by_address'

**Comment by segoz** [comment]
Same problem here... seems like something is broken after the update.

**Comment by Arbuzov** [comment]
[1.2.3](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.2.3) should fix it
