### ISSUE TITLE
no Entity will show

### ISSUE THREAD

**Issue by ha4711** [Arbuzov/home_assistant_delonghi_primadonna#3]
Integration is installed and show (but empty) , name and mac adress was input, but no entity/device is available.

Log:
DelongiPrimadonnaCupLightSwitch(delongh_device)
TypeError: DelonghiDeviceEntity.__init__() missing 1 required positional argument: 'hass'
2022-07-12 16:26:53 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up delonghi_primadonna platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/delonghi_primadonna/binary_sensor.py", line 16, in async_setup_entry
DelongiPrimadonnaCookingSensor(delongh_device)
TypeError: DelonghiDeviceEntity.__init__() missing 1 required positional argument: 'hass'
2022-07-12 16:26:53 ERROR (MainThread) [homeassistant.components.button] Error while setting up delonghi_primadonna platform for button

Versions:
 Home Assistant 2022.7.3 Supervisor 2022.07.0 Operating System 8.2 Frontend 20220707.0 - latest

**Comment by ha4711** [comment]
How can i check, if bluetooth is available on my home assistant?

**Comment by bubez81** [comment]
thank you, with the new release it works!

**Comment by weldingwit** [comment]
Thank you very much - the entities now show up however they do nothing when pressed - and also homeasssistant has gone very slow in loading everything with the integration now installed.

It says also that this uses BLE to connect however there is no Bluetooth on the delonghi primadonna soul - so this is not compatible then?

**Comment by Arbuzov** [comment]
Huh... looks like I am screwed. But, now it should be ok.

**Comment by weldingwit** [comment]
There is no Bluetooth on the delonghi primadonna soul that I can see - only wifi :(

**Comment by weldingwit** [comment]
Support for the delonghi primadonna soul in the future would be nice - but great integration all the same I just bought the wrong coffee machine :)

**Comment by Arbuzov** [comment]
[1.1.0](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.1.0)
