### ISSUE TITLE
ValueError: Sensor sensor.nozzle provides state value '2', which is not in the list of options provided

### ISSUE THREAD

**Issue by codyc1515** [Arbuzov/home_assistant_delonghi_primadonna#54]
I think I am getting this error because it is a different model to the one that you are using. Would need to do some more checking to see what the 2 value is.

```
Logger: homeassistant
Source: components/sensor/__init__.py:572
First occurred: 07:51:15 (32 occurrences)
Last logged: 08:06:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 713, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 572, in state
    raise ValueError(
ValueError: Sensor sensor.nozzle provides state value '2', which is not in the list of options provided
```

**Comment by Arbuzov** [comment]
What was connected to your steam generator then you get this message?

**Comment by codyc1515** [comment]
Machine is not even switched on but does have milk carafe attached to the nozzle

**Comment by codyc1515** [comment]
#80 did not resolve this issue unfortunately. Must be somewhere else.

**Comment by codyc1515** [comment]
Resolved
