### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by codyc1515** [Arbuzov/home_assistant_delonghi_primadonna#83]
Receiving an error in the system log:

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:367
Integration: Binary sensor (documentation, issues)
First occurred: 12:22:47 (1 occurrences)
Last logged: 12:22:47

Error while setting up delonghi_primadonna platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 672, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/delonghi_primadonna/binary_sensor.py", line 66, in icon
    if self.is_on():
       ^^^^^^^^^^^^
TypeError: 'bool' object is not callable
```

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:507
Integration: Binary sensor (documentation, issues)
First occurred: 12:22:47 (1 occurrences)
Last logged: 12:22:47

Error adding entities for domain binary_sensor with platform delonghi_primadonna
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 672, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/delonghi_primadonna/binary_sensor.py", line 66, in icon
    if self.is_on():
       ^^^^^^^^^^^^
TypeError: 'bool' object is not callable
```

Affected code is here: https://github.com/Arbuzov/home_assistant_delonghi_primadonna/blob/b33f9170b3f0c14531f34c6c162a452a761e07e7/custom_components/delonghi_primadonna/binary_sensor.py#L66C25-L66C25

**Comment by codyc1515** [comment]
This may be fixed by the latest changes. Didn't see this on a restart.
