### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by MaxEl3ven** [Arbuzov/home_assistant_delonghi_primadonna#9]
Hi, first of all I want to thank you very much for your hard work! I really appreciate your project! 

Your plugin works fine so far, but I'm getting some Issues with traceback errors - I don't know, if they are really relevant as everything is working fine.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 305, in call
    await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/delonghi_primadonna/device.py", line 257, in get_device_name
    await self._connect()
  File "/config/custom_components/delonghi_primadonna/device.py", line 157, in _connect
    await self._client.connect()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 156, in connect
    reply = await asyncio.wait_for(
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by Arbuzov** [comment]
[1.2.3](https://github.com/Arbuzov/home_assistant_delonghi_primadonna/releases/tag/1.2.3) should should fix it
